import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
import { Providers } from "./components/Providers/Providers";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  themeColor: "#ffffff",
  title: "Symptologix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
