import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import AuthProvider from "./components/authprovider/AuthProvider";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
