import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
import AuthProvider from "./components/authprovider/AuthProvider";

export const metadata: Metadata = {
  title: "Smyptologix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
